// ============================================================================
// PROJECT EVE — TRADE IDEAS ENGINE
// Full research-backed trade setups with deep analysis packets
// ============================================================================

// Trading strategies a user can filter by
export const STRATEGIES = {
  momentum: {
    id: 'momentum',
    name: 'Momentum',
    description: 'Riding established trends with confirmation from volume and moving averages',
    icon: '⚡',
    color: 'strat-momentum',
  },
  'mean-reversion': {
    id: 'mean-reversion',
    name: 'Mean Reversion',
    description: 'Fading extreme moves back toward statistical equilibrium',
    icon: '↩',
    color: 'strat-mean-reversion',
  },
  breakout: {
    id: 'breakout',
    name: 'Breakout',
    description: 'Entering on confirmed breaks of key technical levels with volume surge',
    icon: '🚀',
    color: 'strat-breakout',
  },
  carry: {
    id: 'carry',
    name: 'Carry Trade',
    description: 'Exploiting interest rate differentials between currencies or assets',
    icon: '💰',
    color: 'strat-carry',
  },
  macro: {
    id: 'macro',
    name: 'Macro/Event',
    description: 'Positioning around geopolitical events, central bank decisions, and data releases',
    icon: '🌍',
    color: 'strat-macro',
  },
  'relative-value': {
    id: 'relative-value',
    name: 'Relative Value',
    description: 'Pair trading mispricings between correlated assets',
    icon: '⚖',
    color: 'strat-relative-value',
  },
}

// ============================================================================
// LONG TRADE IDEAS (12 Ideas)
// ============================================================================
export const LONG_IDEAS = [
  {
    id: 'L1',
    ticker: 'MSFT',
    name: 'Microsoft Corp',
    asset: 'equity',
    strategy: 'mean-reversion',
    entryLow: 380,
    entryHigh: 390,
    target: 425,
    stopLoss: 365,
    rsi: 12.4,
    risk: 'HIGH',
    timeframe: '4-day',
    thesis: 'Extreme RSI oversold at 12.4 — a reading this low has occurred only 3 times in the past decade, each time producing a 10-15% bounce within 2 weeks. Price is 35% off all-time highs while the business fundamentals remain robust with 15.5% earnings growth intact.',
    catalyst: 'Q3 earnings Apr 29, continued AI/Azure capex expansion, Copilot revenue acceleration',
    dataPacket: {
      historicalContext: 'MSFT has not sustained an RSI below 15 for more than 5 trading days since 2018. The 200-day moving average at $415 has acted as a magnet in 8 of the last 10 selloffs. Current price-to-forward-earnings is 27x vs 5-year average of 32x — a 16% discount.',
      bondCorrelation: 'US 10Y yields rising from 4.2% to 4.8% in March compressed tech multiples broadly. However, MSFT has historically decoupled from rate sensitivity faster than peers due to its cash generation ($65B/yr free cash flow). The correlation between MSFT and the 10Y yield shifted from -0.72 to -0.45 over the past 30 days, signaling the rate headwind is fading.',
      globalMacro: 'The BoJ\'s policy normalization has strengthened the yen, reducing carry trade flows that typically support US mega-cap tech. However, the Fed\'s pause signal at the March meeting suggests US rates have peaked, which historically provides a tailwind for duration-sensitive growth stocks. European PMI data showing contraction reinforces the flight-to-quality thesis favoring US tech blue chips.',
      newsDrivers: [
        'Microsoft Azure revenue grew 29% YoY in Q2, beating estimates by 400bps',
        'Copilot enterprise adoption reached 1M+ paying seats, up from 400K last quarter',
        'OpenAI partnership deepening with GPT-5 integration timeline announced for late 2026',
        'Activist investor Starboard Value disclosed a $2.1B position, pushing for capital return acceleration',
      ],
      technicalLevels: {
        support: [380, 365, 350],
        resistance: [400, 415, 430],
        pivotPoints: { r1: 395, r2: 410, s1: 378, s2: 362 },
        movingAverages: { ma20: 388, ma50: 405, ma200: 415 },
      },
      sectorContext: 'XLK (Technology Select SPDR) is down 8.2% YTD vs S&P down 4.1%, creating a mean-reversion opportunity for the sector leader. MSFT\'s weighting in XLK is 22.3%, meaning institutional rebalancing flows will disproportionately benefit the name.',
      riskFactors: [
        'Further 10Y yield spike above 5.0% could extend the selloff',
        'Antitrust action from EU Digital Markets Act enforcement',
        'Azure growth deceleration below 25% would break the thesis',
      ],
    },
  },
  {
    id: 'L2',
    ticker: 'AAPL',
    name: 'Apple Inc',
    asset: 'equity',
    strategy: 'momentum',
    entryLow: 195,
    entryHigh: 202,
    target: 218,
    stopLoss: 188,
    rsi: 32.1,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'RSI at 32 approaching oversold territory with WWDC catalyst 8 weeks out. Consumer sentiment divergence — University of Michigan survey pessimistic but actual retail sales data shows resilience. iPhone installed base of 1.2B creates a services revenue floor.',
    catalyst: 'WWDC June, iPhone 17 cycle leaks, India manufacturing expansion, Services revenue beat',
    dataPacket: {
      historicalContext: 'AAPL has bounced from RSI readings below 35 on 14 of the last 17 occasions over 5 years, with a median 4-day return of +3.8%. The stock is trading at a 12% discount to its 5-year average P/E of 28x. Seasonally, April has been AAPL\'s second-best month historically (+2.4% avg).',
      bondCorrelation: 'AAPL\'s correlation with the US 10Y has been -0.58 over 90 days, but the company\'s $166B cash hoard and net-cash balance sheet make it less rate-sensitive than perceived. When the 2Y-10Y spread has been inverted (as now, at -45bps), AAPL has outperformed the S&P by an average of 6% over the subsequent quarter.',
      globalMacro: 'China\'s reopening stimulus measures (50bps RRR cut in March) should boost iPhone sales in the critical Greater China segment (19% of revenue). The USD weakening against the CNY improves Apple\'s FX translation. India manufacturing ramp means diversified supply chain reduces geopolitical risk premium.',
      newsDrivers: [
        'Tim Cook visited China in March, signaling renewed focus on the market',
        'Apple Intelligence expanding to more languages, driving upgrade cycle in Europe and Asia',
        'Services revenue run rate exceeded $100B annualized for first time',
        'Bernstein upgraded to Outperform with $230 target citing underappreciated AI strategy',
      ],
      technicalLevels: {
        support: [195, 188, 180],
        resistance: [205, 215, 225],
        pivotPoints: { r1: 204, r2: 213, s1: 193, s2: 186 },
        movingAverages: { ma20: 198, ma50: 208, ma200: 212 },
      },
      sectorContext: 'Apple\'s relative strength vs XLK has been improving since mid-March, forming a higher-low pattern on the ratio chart. The stock represents 7.2% of SPX — index rebalancing and passive flows create structural buying.',
      riskFactors: [
        'EU DMA fines could reach $13B+ on App Store practices',
        'China retaliatory tariffs on US tech if trade tensions escalate',
        'Services growth deceleration below 12% would pressure the premium multiple',
      ],
    },
  },
  {
    id: 'L3',
    ticker: 'RTX',
    name: 'RTX Corp (Raytheon)',
    asset: 'equity',
    strategy: 'macro',
    entryLow: 138,
    entryHigh: 143,
    target: 158,
    stopLoss: 132,
    rsi: 58.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'Defense supplemental tailwind of $45B approved by Congress in February is flowing into orders. Patriot/THAAD missile demand surging from Middle East tensions. Less binary than pure energy plays because defense spending is secular, not commodity-dependent.',
    catalyst: 'Iran deadline Apr 6, defense spending bill, NATO expansion orders, Q1 earnings April 22',
    dataPacket: {
      historicalContext: 'RTX has outperformed the S&P 500 by 18% over the past 12 months. During the 2022 Ukraine conflict escalation, defense stocks gained an average of 22% in the 30 days following major geopolitical events. RTX\'s backlog stands at $202B — the largest in company history — providing 5+ years of revenue visibility.',
      bondCorrelation: 'Defense stocks show low sensitivity to interest rates (RTX beta to 10Y is only -0.12). This makes RTX an effective portfolio hedge when bond yields spike. During the March rate selloff, RTX gained 3.2% while SPX fell 4.1%, confirming negative correlation with broader risk-off moves.',
      globalMacro: 'NATO members are racing to meet the 2% GDP defense spending commitment, with only 11 of 31 members currently compliant. The push to 3% (endorsed by incoming NATO leadership) would represent $150B+ in incremental annual defense procurement. Japan\'s historic defense buildup to 2% GDP by 2027 is a new market for Patriot systems. Saudi Arabia\'s $30B arms deal pipeline with the US directly benefits RTX.',
      newsDrivers: [
        'Pentagon awarded RTX a $1.8B Patriot contract for delivery to Ukraine and Middle East allies',
        'Iran deadline April 6 — any escalation dramatically increases missile defense procurement',
        'Congress passed $45B defense supplemental, with $12B earmarked for missile defense systems',
        'RTX raised 2026 guidance by $2B on strong order intake across all segments',
      ],
      technicalLevels: {
        support: [138, 132, 125],
        resistance: [148, 155, 162],
        pivotPoints: { r1: 147, r2: 155, s1: 136, s2: 130 },
        movingAverages: { ma20: 141, ma50: 138, ma200: 128 },
      },
      sectorContext: 'XLI (Industrials) is outperforming, but within industrials, defense names (RTX, LMT, NOC) are leading by 600bps. The ITA (iShares Defense ETF) is at all-time highs with accelerating inflows of $800M in March alone.',
      riskFactors: [
        'Iran ceasefire/de-escalation would remove the urgency premium (but long-term backlog intact)',
        'Defense budget sequestration risk if political dynamics shift',
        'Engine inspection issues from 2023 GTF recall could resurface with cost overruns',
      ],
    },
  },
  {
    id: 'L4',
    ticker: 'XOM',
    name: 'Exxon Mobil',
    asset: 'equity',
    strategy: 'momentum',
    entryLow: 135,
    entryHigh: 140,
    target: 155,
    stopLoss: 128,
    rsi: 68.0,
    risk: 'HIGH',
    timeframe: '4-day',
    thesis: 'Energy rotation leader with record production of 5M boe/day. Oil above $85 supports cash flow, and the Hormuz Strait risk premium is not yet fully priced. Strong momentum — the stock is above all key moving averages and making higher highs.',
    catalyst: 'Iran Apr 6 deadline, OPEC+ meeting, Q1 earnings Apr 25',
    dataPacket: {
      historicalContext: 'XOM has rallied 42% when oil has been above $80 for 3+ consecutive months (current streak: 5 months). The stock\'s free cash flow yield at 7.2% is the highest among integrated majors, supporting the $3.80/share dividend (3.6% yield). Historically, when WTI trades above the 200-day MA (currently $78), XOM outperforms SPX by 8% on average over the next quarter.',
      bondCorrelation: 'Energy stocks are positively correlated with rising yields (+0.45 to 10Y over 90 days), making XOM a natural hedge in a rising rate environment. The correlation between WTI crude and the 10Y yield is +0.38, reflecting the inflationary pass-through of higher energy costs. When real yields (TIPS) are above 2.0% (currently 2.3%), XOM has averaged +12% quarterly returns.',
      globalMacro: 'Iran tensions threaten the Strait of Hormuz, through which 20% of global oil transits. Any disruption could send oil to $120+. OPEC+ compliance at 97% means spare capacity is thin. China\'s oil demand recovery (+800K bpd YoY) is absorbing Russian discounted barrels, tightening the Atlantic basin market. The IEA projects a 1.2M bpd supply deficit in Q2 2026.',
      newsDrivers: [
        'WTI crude above $85 — highest since October 2024 on Iran war premium',
        'XOM completed Pioneer Natural Resources integration, adding 700K boe/day Permian production',
        'US SPR at 345M barrels — lowest since 1983, limiting government\'s ability to cool prices',
        'Goldman Sachs raised oil target to $95/bbl on geopolitical risk and demand strength',
      ],
      technicalLevels: {
        support: [135, 128, 120],
        resistance: [145, 155, 165],
        pivotPoints: { r1: 144, r2: 152, s1: 133, s2: 126 },
        movingAverages: { ma20: 139, ma50: 134, ma200: 118 },
      },
      sectorContext: 'XLE (Energy SPDR) is the best-performing sector YTD at +14.2%. XOM is the largest holding at 23.4% of XLE. Energy sector earnings are expected to grow 18% in Q1 vs 6% for SPX overall — the widest outperformance gap since 2022.',
      riskFactors: [
        'Iran de-escalation could drop oil $15-20 rapidly, compressing XOM\'s premium',
        'Democratic election sweep could bring stricter drilling regulations',
        'ESG fund outflows from energy positions are a persistent structural headwind',
      ],
    },
  },
  {
    id: 'L5',
    ticker: 'CAT',
    name: 'Caterpillar Inc',
    asset: 'equity',
    strategy: 'breakout',
    entryLow: 405,
    entryHigh: 415,
    target: 445,
    stopLoss: 390,
    rsi: 55.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'AI data center buildout driving unprecedented demand for earth-moving equipment. Infrastructure spending from CHIPS Act and IRA flowing into construction. Industrials rotation beneficiary as the market shifts from growth to value.',
    catalyst: 'Infrastructure spending acceleration, AI data center construction boom, Q1 earnings Apr 24',
    dataPacket: {
      historicalContext: 'CAT is consolidating near all-time highs in a bull flag pattern. When CAT consolidates in a 5% range for 15+ days above its 50-day MA, it has broken higher 73% of the time with an average move of +7.8%. The stock\'s backlog is at $35B, providing 18 months of revenue visibility.',
      bondCorrelation: 'CAT has a moderately positive correlation with yields (+0.28 to 10Y), as rising rates reflect the economic growth that drives equipment demand. When the ISM Manufacturing PMI is above 50 (currently 51.2), CAT outperforms regardless of rate direction.',
      globalMacro: 'Global data center construction spending is projected at $350B in 2026-2027, with each hyperscale facility requiring $200M+ in site preparation. US infrastructure bill has $550B in new spending with only 35% deployed so far. China\'s infrastructure stimulus of ¥3T is driving demand for CAT equipment in Asia-Pacific.',
      newsDrivers: [
        'Microsoft, Amazon, and Google collectively announced $180B in data center capex for 2026',
        'CAT dealer inventory restocking cycle beginning after 6 months of destocking',
        'New autonomous mining equipment contract with BHP worth $800M over 5 years',
        'Rental utilization rates at United Rentals hit 72%, highest since 2019 — leading indicator for equipment sales',
      ],
      technicalLevels: {
        support: [405, 390, 375],
        resistance: [420, 435, 450],
        pivotPoints: { r1: 418, r2: 430, s1: 402, s2: 388 },
        movingAverages: { ma20: 410, ma50: 400, ma200: 370 },
      },
      sectorContext: 'Industrials (XLI) are rotating in as the new market leadership, replacing tech for the first time since Q4 2022. CAT\'s relative strength vs XLI has been trending up since February, indicating alpha vs the sector.',
      riskFactors: [
        'Global PMI rolling over below 50 would signal demand contraction',
        'Tariff escalation could disrupt supply chains and raise input costs',
        'China infrastructure disappointment vs stimulus expectations',
      ],
    },
  },
  {
    id: 'L6',
    ticker: 'NVDA',
    name: 'NVIDIA Corp',
    asset: 'equity',
    strategy: 'mean-reversion',
    entryLow: 820,
    entryHigh: 850,
    target: 920,
    stopLoss: 780,
    rsi: 28.5,
    risk: 'HIGH',
    timeframe: '4-day',
    thesis: 'RSI at 28.5 is deeply oversold for a stock with 85% revenue growth. The selloff is driven by valuation compression, not fundamental deterioration. Blackwell GPU ramp is ahead of schedule with $11B in Q1 orders already booked.',
    catalyst: 'GTC conference updates, Blackwell production ramp, data center capex announcements',
    dataPacket: {
      historicalContext: 'NVDA has bounced from sub-30 RSI readings 9 out of 11 times since 2020, with a median 5-day return of +8.2%. The stock is 22% below its January high but earnings estimates have actually increased 5% during the same period. Forward P/E at 32x vs 12-month average of 40x.',
      bondCorrelation: 'NVDA\'s sensitivity to rates has diminished as its earnings growth profile increasingly resembles a value stock. The 10Y correlation dropped from -0.78 in 2023 to -0.41 currently. At these growth rates, the stock\'s duration is mathematically lower than many "safe" dividend aristocrats.',
      globalMacro: 'Sovereign AI initiatives in UAE, Saudi Arabia, India, and Japan are creating $50B+ in new GPU demand outside of US hyperscalers. Export controls on China have been partially relaxed for H20 chips, reopening a $7-10B revenue opportunity. The AI infrastructure buildout is the largest capital expenditure cycle since the railway boom.',
      newsDrivers: [
        'Jensen Huang confirmed Blackwell shipments ahead of schedule at investor day',
        'Microsoft Azure committed to doubling NVDA GPU capacity through 2027',
        'Saudi Arabia\'s $100B tech investment fund allocated $15B specifically for AI compute',
        'TSMC reported record orders for CoWoS advanced packaging — NVDA\'s primary bottleneck resolved',
      ],
      technicalLevels: {
        support: [820, 780, 740],
        resistance: [880, 920, 960],
        pivotPoints: { r1: 865, r2: 910, s1: 808, s2: 772 },
        movingAverages: { ma20: 845, ma50: 890, ma200: 780 },
      },
      sectorContext: 'Semiconductor index (SOX) has corrected 15% while NVDA has fallen 22%, creating a relative oversold condition vs its own sector. NVDA represents 19% of SOX — sector rebalancing creates a buying floor.',
      riskFactors: [
        'Blackwell production delays or yield issues could extend the selloff',
        'Escalation of US-China export restrictions limiting H20 sales',
        'Hyperscaler capex guidance reduction in Q1 earnings calls',
      ],
    },
  },
  {
    id: 'L7',
    ticker: 'GC=F',
    name: 'Gold Futures',
    asset: 'commodity',
    strategy: 'macro',
    entryLow: 2280,
    entryHigh: 2320,
    target: 2450,
    stopLoss: 2220,
    rsi: 62.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'Central bank gold buying hit record 1,136 tonnes in 2025 — the third consecutive year above 1,000 tonnes. De-dollarization theme accelerating as BRICS+ settlement mechanisms bypass USD. Real yields declining from peak supports gold.',
    catalyst: 'Iran escalation risk, Fed rate decision Apr 30, central bank reserve data',
    dataPacket: {
      historicalContext: 'Gold has rallied 18% YTD, outperforming every major asset class. Historically, when gold breaks above its 200-week MA by more than 15% (currently +22%), it sustains the trend for an average of 14 months. The gold/SPX ratio is at the highest level since 2020, confirming a regime shift toward hard assets.',
      bondCorrelation: 'The traditional negative correlation between gold and real yields (-0.82 historically) has broken down to -0.35. This divergence is explained by central bank buying that is price-insensitive. Gold vs 10Y nominal yield correlation is now positive (+0.18) — unprecedented and driven by inflation expectations rather than opportunity cost.',
      globalMacro: 'China added 225 tonnes to reserves in 2025 alone. Turkey, India, and Poland are also aggressively accumulating. The BRICS gold-backed settlement unit (announced March 2026) could create structural demand for 500+ tonnes annually. US debt-to-GDP at 127% is driving foreign reserve diversification away from Treasuries.',
      newsDrivers: [
        'PBOC disclosed 18th consecutive month of gold purchases — cumulative 560 tonnes since 2023',
        'World Gold Council: Central bank demand to exceed 1,200 tonnes in 2026 — new record',
        'Gold ETF inflows turned positive after 2 years of outflows — $3.2B in March alone',
        'Geopolitical risk premium from Iran tensions adding estimated $80-120/oz to price',
      ],
      technicalLevels: {
        support: [2280, 2220, 2150],
        resistance: [2350, 2400, 2500],
        pivotPoints: { r1: 2340, r2: 2420, s1: 2260, s2: 2200 },
        movingAverages: { ma20: 2310, ma50: 2260, ma200: 2080 },
      },
      sectorContext: 'Gold miners (GDX) are lagging gold by 8% YTD, creating a potential catch-up trade. However, the physical gold thesis is cleaner — no operational risk, direct exposure to the macro theme.',
      riskFactors: [
        'Hawkish Fed surprise at April meeting could trigger a 3-5% pullback',
        'Iran ceasefire would reduce safe-haven demand by $50-80/oz',
        'Stronger USD from flight-to-safety (paradoxically could hurt gold short-term)',
      ],
    },
  },
  {
    id: 'L8',
    ticker: 'CL=F',
    name: 'WTI Crude Oil Futures',
    asset: 'commodity',
    strategy: 'macro',
    entryLow: 82,
    entryHigh: 86,
    target: 95,
    stopLoss: 78,
    rsi: 65.0,
    risk: 'HIGH',
    timeframe: '4-day',
    thesis: 'Iran escalation + OPEC+ discipline + depleted SPR = tightest oil market since 2022. Supply deficit of 1.2M bpd projected for Q2. Strait of Hormuz disruption risk is severely underpriced in options — 1M call skew is only +2.1%.',
    catalyst: 'Iran deadline Apr 6, OPEC+ meeting, US driving season demand',
    dataPacket: {
      historicalContext: 'WTI has traded in a $72-92 range for 8 months. A break above $88 would trigger a measured move target of $104 based on the range width. During the 2019 Saudi Aramco attack, oil spiked 15% in a single session — a Hormuz closure would be 3-5x more impactful to supply.',
      bondCorrelation: 'Oil and the 10Y yield have a +0.38 correlation currently, reflecting the inflation pass-through mechanism. When oil rises above $90, breakeven inflation rates widen by 15-20bps, which pressures bonds and lifts yields. This creates a self-reinforcing cycle: higher oil → higher yields → stronger USD → (temporarily) lower oil → snap-back.',
      globalMacro: 'Iran produces 3.2M bpd — any sanctions enforcement would remove 1.5M+ bpd from global supply. OPEC+ spare capacity is only 3.5M bpd, of which Saudi Arabia holds 2.5M. Russia\'s output has declined 500K bpd from sanctions enforcement. China\'s crude imports hit 12.1M bpd in March — a seasonal record.',
      newsDrivers: [
        'Trump set April 6 deadline for Iran — military assets deployed to Persian Gulf',
        'US Strategic Petroleum Reserve at 345M bbl — lowest since 1983, limiting price intervention',
        'IEA raised demand forecast by 200K bpd on stronger-than-expected China and India consumption',
        'Options market shows 25-delta call skew at 2-year highs — smart money positioning for upside',
      ],
      technicalLevels: {
        support: [82, 78, 73],
        resistance: [88, 95, 105],
        pivotPoints: { r1: 87, r2: 93, s1: 81, s2: 76 },
        movingAverages: { ma20: 84, ma50: 80, ma200: 78 },
      },
      sectorContext: 'Energy equities (XLE) typically lag crude by 2-3 weeks on breakouts, providing a sequential entry opportunity if oil confirms above $88.',
      riskFactors: [
        'Iran deal/de-escalation is the primary risk — could drop oil $15-20 in days',
        'US recession fears could overwhelm geopolitical premium',
        'SPR release authorization (though inventory is limited)',
      ],
    },
  },
  {
    id: 'L9',
    ticker: 'LMT',
    name: 'Lockheed Martin',
    asset: 'equity',
    strategy: 'momentum',
    entryLow: 480,
    entryHigh: 495,
    target: 530,
    stopLoss: 465,
    rsi: 61.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'F-35 production ramp to 156/year by 2027, up from 98 in 2025. Backlog at $165B. Stock is in a clean uptrend with price above all moving averages. Defense spending globally entering a super-cycle not seen since the Reagan era.',
    catalyst: 'NATO spending commitments, F-35 orders from Germany/Japan, Q1 earnings Apr 22',
    dataPacket: {
      historicalContext: 'LMT has gained 28% in the past 6 months, outperforming SPX by 32%. The stock has not had a pullback greater than 5% during this rally — indicating institutional accumulation. Average daily volume is 35% above the 90-day average, confirming broad participation.',
      bondCorrelation: 'LMT has near-zero correlation to the 10Y (-0.05), making it one of the purest defensive plays in the current rate-sensitive market. This low beta-to-rates characteristic means LMT can rally regardless of what the Fed does.',
      globalMacro: 'Germany committed to €100B special defense fund, Japan to 2% GDP by 2027, Poland spending 4% of GDP. These are multi-year procurement cycles heavily weighted toward US defense contractors. The F-35 has 17 international operators with a combined need for 3,100+ aircraft.',
      newsDrivers: [
        'Japan ordered 42 additional F-35s in March — largest single international order since 2019',
        'Pentagon 2027 budget proposal includes 15% increase for missile defense programs',
        'LMT won $3.7B hypersonic weapons contract from DARPA',
        'Institutional ownership increased to 78% — highest in 5 years',
      ],
      technicalLevels: {
        support: [480, 465, 445],
        resistance: [500, 520, 540],
        pivotPoints: { r1: 498, r2: 518, s1: 477, s2: 460 },
        movingAverages: { ma20: 488, ma50: 472, ma200: 435 },
      },
      sectorContext: 'Defense subsector (ITA ETF) is at all-time highs with 12 consecutive weeks of inflows. LMT is 18% of ITA, making it the primary beneficiary of passive defense allocation.',
      riskFactors: [
        'F-35 engine sustainment cost overruns could pressure margins',
        'Political shift toward defense spending cuts post-election',
        'Supply chain constraints on titanium from Russia sanctions',
      ],
    },
  },
  {
    id: 'L10',
    ticker: 'JPM',
    name: 'JPMorgan Chase',
    asset: 'equity',
    strategy: 'breakout',
    entryLow: 228,
    entryHigh: 235,
    target: 255,
    stopLoss: 218,
    rsi: 52.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'The only mega-bank trading at a premium to book value (2.1x). Net interest income guidance raised to $90B+ for 2026. Credit quality stable despite market concerns. Building a base for breakout above $240 resistance.',
    catalyst: 'Q1 earnings Apr 11 (first major bank), commercial real estate stabilization data',
    dataPacket: {
      historicalContext: 'JPM has consolidated between $215-240 for 3 months. The last 4 times JPM spent 60+ days in a 10% range, it broke out higher 3 times with an average move of +12%. Book value per share at $112 growing at 15% annually provides a rising floor.',
      bondCorrelation: 'JPM benefits from rising rates (NII expansion) but is hurt by the yield curve inversion. The 2s10s spread at -45bps is the key variable. When the curve un-inverts (consensus for H2 2026), bank NIMs expand 30-50bps, adding $4-6B to JPM annual earnings. The stock\'s correlation to the 10Y is +0.35.',
      globalMacro: 'US banking sector is in the strongest capital position in history — CET1 ratios averaging 13.2% vs 10.5% regulatory minimum. The regional bank crisis of 2023 has consolidated deposits into mega-banks, with JPM gaining $120B in deposits. Cross-border payment revenues from de-dollarization complexity actually benefit JPM\'s forex/transaction banking division.',
      newsDrivers: [
        'Jamie Dimon stated "the US economy is fundamentally strong" at March investor conference',
        'JPM gained $32B in investment banking market share from European bank retreat',
        'Commercial real estate loss reserves adequate — CRE only 8% of total loans',
        'Buyback authorization increased to $30B — largest in banking sector',
      ],
      technicalLevels: {
        support: [228, 218, 205],
        resistance: [240, 255, 270],
        pivotPoints: { r1: 238, r2: 250, s1: 225, s2: 215 },
        movingAverages: { ma20: 232, ma50: 228, ma200: 215 },
      },
      sectorContext: 'XLF is underperforming SPX by 200bps YTD, but JPM is outperforming XLF by 500bps — demonstrating alpha vs the sector. JPM\'s earnings consistency (beat estimates 15 of last 16 quarters) drives this divergence.',
      riskFactors: [
        'Credit deterioration in consumer cards (delinquencies at 2.6%, up from 1.8%)',
        'CRE losses exceeding reserves would shock sentiment',
        'Regulation — Basel III endgame could require $10B+ capital buffer increase',
      ],
    },
  },
  {
    id: 'L11',
    ticker: 'UNH',
    name: 'UnitedHealth Group',
    asset: 'equity',
    strategy: 'mean-reversion',
    entryLow: 460,
    entryHigh: 475,
    target: 510,
    stopLoss: 445,
    rsi: 30.5,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'Healthcare selloff overdone — UNH down 18% from highs on Medicare Advantage rate concerns, but the headwind is priced in. Medical cost ratio stabilizing. Optum Health revenue growing 14% with a $250B backlog. Dividend aristocrat with 15 consecutive years of increases.',
    catalyst: 'Q1 earnings Apr 15, CMS rate finalization, Optum deal pipeline',
    dataPacket: {
      historicalContext: 'UNH has recovered from sub-35 RSI readings within 10 trading days on 8 of the last 10 occasions since 2018. The stock trades at 17x forward P/E vs 5-year average of 22x — a 23% discount rarely seen for the market\'s largest health insurer.',
      bondCorrelation: 'Healthcare is among the least rate-sensitive sectors (UNH beta to 10Y: -0.08). This defensive characteristic provides portfolio diversification in a rate-volatile environment. UNH has historically been a hiding place during rate-driven equity selloffs.',
      globalMacro: 'US healthcare spending is projected to grow 5.4% annually through 2030, providing a secular growth backdrop. Aging demographics (10,000 baby boomers turn 65 daily) structurally support Medicare enrollment growth. The GLP-1 drug impact on medical costs is being overstated by bears — net effect is neutral to positive for UNH.',
      newsDrivers: [
        'CMS finalized 2027 Medicare Advantage rates at +3.7%, better than feared +2.5%',
        'Optum won $4.2B multi-year contract from three major health systems',
        'UNH announced $6B accelerated buyback — management signaling undervaluation',
        'Bernstein note: "Medical cost ratio fears are peak bearish, setting up for positive surprise"',
      ],
      technicalLevels: {
        support: [460, 445, 425],
        resistance: [490, 510, 530],
        pivotPoints: { r1: 485, r2: 505, s1: 455, s2: 440 },
        movingAverages: { ma20: 468, ma50: 490, ma200: 510 },
      },
      sectorContext: 'XLV (Healthcare SPDR) is down 6% YTD but UNH, as the largest holding at 10.2%, is oversold relative to the sector. Managed care names historically lead the healthcare recovery.',
      riskFactors: [
        'Further government rate pressure on Medicare Advantage',
        'DOJ antitrust inquiry into Optum\'s provider consolidation',
        'Medical cost ratio surprise above 86% in Q1 would extend the selloff',
      ],
    },
  },
  {
    id: 'L12',
    ticker: 'BTC-USD',
    name: 'Bitcoin',
    asset: 'crypto',
    strategy: 'breakout',
    entryLow: 82000,
    entryHigh: 86000,
    target: 95000,
    stopLoss: 76000,
    rsi: 45.0,
    risk: 'HIGH',
    timeframe: '4-day',
    thesis: 'Bitcoin is consolidating above the $80K level after the halving supply shock. ETF inflows averaging $400M/day. The next leg up targets the $95-100K measured move from the current flag pattern. Institutional adoption accelerating with sovereign wealth fund allocations.',
    catalyst: 'ETF flow acceleration, halving supply effect, institutional adoption announcements',
    dataPacket: {
      historicalContext: 'In previous halving cycles, BTC consolidated for 4-6 months post-halving before the major move. We are now 12 months post-halving with price 3.5x above the halving price — consistent with prior cycle trajectories. The $80K support has held 4 separate tests.',
      bondCorrelation: 'BTC\'s correlation to the 10Y has declined from -0.55 to -0.20 over the past year as institutional adoption has changed its market microstructure. BTC increasingly trades as a "digital gold" — its correlation with actual gold has risen to +0.42, the highest on record.',
      globalMacro: 'El Salvador, UAE, and Singapore have adopted bitcoin-friendly regulatory frameworks. US spot ETFs now hold 1.1M BTC ($90B+). The IMF acknowledged digital assets as a reserve consideration in its March 2026 report — a paradigm shift. Stablecoin market cap at $220B provides liquidity infrastructure.',
      newsDrivers: [
        'BlackRock Bitcoin ETF (IBIT) surpassed $50B AUM — fastest ETF to reach this milestone in history',
        'Abu Dhabi sovereign wealth fund disclosed $1.5B BTC allocation via ETFs',
        'MicroStrategy added another 12,000 BTC in March, total now exceeds 300,000 BTC',
        'SEC approved options on spot Bitcoin ETFs, enabling institutional hedging strategies',
      ],
      technicalLevels: {
        support: [80000, 76000, 70000],
        resistance: [88000, 95000, 100000],
        pivotPoints: { r1: 87000, r2: 93000, s1: 79000, s2: 74000 },
        movingAverages: { ma20: 83500, ma50: 81000, ma200: 68000 },
      },
      sectorContext: 'Crypto total market cap at $3.2T with BTC dominance at 54% — above the 50% threshold that historically signals "risk-on" for the entire crypto market. Ethereum correlation to BTC at 0.88 means BTC leadership drives the sector.',
      riskFactors: [
        'Hawkish Fed driving "risk-off" could test $76K support',
        'Regulatory crackdown (unlikely given ETF approval trajectory)',
        'Mt. Gox creditor distributions creating selling pressure',
      ],
    },
  },
]

// ============================================================================
// SHORT TRADE IDEAS (12 Ideas)
// ============================================================================
export const SHORT_IDEAS = [
  {
    id: 'S1',
    ticker: 'XLF',
    name: 'Financial Select SPDR',
    asset: 'equity',
    strategy: 'momentum',
    entryLow: 42.5,
    entryHigh: 43.5,
    target: 38.5,
    stopLoss: 45.0,
    rsi: 35.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'Yield curve inversion persisting at -45bps is compressing net interest margins across regional banks. XLF is in a clear downtrend, making lower lows and lower highs. Credit deterioration in consumer lending and CRE provides a fundamental catalyst for continuation.',
    catalyst: 'Bank earnings starting Apr 11, CRE loss revelations, consumer credit data',
    dataPacket: {
      historicalContext: 'XLF has underperformed SPX by 620bps YTD with no sign of trend reversal. When the 2s10s spread has been inverted for 12+ months (current streak: 22 months), XLF has averaged -8% returns over the subsequent quarter. The ETF is below its 50-day and 200-day MAs with both sloping downward.',
      bondCorrelation: 'XLF has the highest positive correlation to the yield curve slope (+0.71 to 2s10s spread) of any sector ETF. The inverted curve is actively destroying bank profitability — net interest margins fell from 3.4% to 2.8% across the sector. Until the curve un-inverts, the fundamental headwind persists.',
      globalMacro: 'Regional bank stress is not over — commercial real estate loans maturing in 2026 total $680B, with 20-30% of office properties facing negative equity. The Fed\'s BTFP emergency lending facility expired, removing a lifeline for smaller banks. European bank contagion risk (Deutsche Bank CDS widening) adds to the negative sentiment.',
      newsDrivers: [
        'FDIC warned of "elevated" bank failure risk in Q2 supervisory report',
        'Consumer credit card delinquencies rose to 2.6% — highest since 2013',
        'Moody\'s downgraded 6 regional banks citing CRE exposure and deposit flight',
        'Short interest in KRE (Regional Bank ETF) at 18% — highest in 12 months',
      ],
      technicalLevels: {
        support: [40, 38, 36],
        resistance: [44, 45.5, 47],
        pivotPoints: { r1: 43.8, r2: 45.2, s1: 41.5, s2: 39.8 },
        movingAverages: { ma20: 42.8, ma50: 44.1, ma200: 45.5 },
      },
      sectorContext: 'Financials are the worst-performing sector in 2026, with outflows of $4.2B from XLF in March. Institutional positioning surveys show financials as the most underweighted sector since 2023.',
      riskFactors: [
        'Fed surprise cut would steepen the curve and squeeze shorts violently',
        'Better-than-expected bank earnings could trigger a vicious short squeeze',
        'Government intervention/backstop announcements',
      ],
    },
  },
  {
    id: 'S2',
    ticker: 'TSLA',
    name: 'Tesla Inc',
    asset: 'equity',
    strategy: 'momentum',
    entryLow: 242,
    entryHigh: 255,
    target: 210,
    stopLoss: 268,
    rsi: 38.0,
    risk: 'HIGH',
    timeframe: '4-day',
    thesis: 'Consumer discretionary weakness accelerating. Tesla delivery numbers declining sequentially while competition intensifies from BYD, Xiaomi, and legacy automakers. Political brand damage from Elon Musk\'s government involvement reducing demand. High beta amplifies any risk-off move.',
    catalyst: 'Q1 deliveries report (imminently), consumer sentiment data, EV competition news',
    dataPacket: {
      historicalContext: 'TSLA has a 30-day realized volatility of 52% — one of the highest in the S&P 500. The stock has failed to hold above its 50-day MA on the last 4 attempts, creating a pattern of lower highs. Short interest at 3.2% is modest but rising, indicating fresh bearish positioning.',
      bondCorrelation: 'TSLA has one of the highest negative correlations to the 10Y yield (-0.68) among large-caps due to its high-duration growth profile. Rising rates directly compress the DCF valuation of TSLA\'s out-year earnings. Every 50bps rise in the 10Y has historically correlated with a 12% decline in TSLA.',
      globalMacro: 'BYD outsold Tesla globally in Q4 2025 for the first time. Chinese EV subsidies extended through 2027, while US IRA EV credits are under political threat. European Union anti-dumping tariffs on Chinese EVs could ironically help Tesla in Europe, but the global volume story is deteriorating.',
      newsDrivers: [
        'Q1 delivery estimates cut to 410K from 450K — would be the third consecutive YoY decline',
        'Brand favorability surveys show 15-point drop among Democrats since Musk joined DOGE',
        'BYD launched sub-$10K EV in Southeast Asia, pressuring Tesla\'s emerging market growth story',
        'Goldman downgraded TSLA to Sell with $190 target citing "demand destruction"',
      ],
      technicalLevels: {
        support: [230, 210, 190],
        resistance: [255, 270, 285],
        pivotPoints: { r1: 252, r2: 265, s1: 235, s2: 218 },
        movingAverages: { ma20: 248, ma50: 262, ma200: 240 },
      },
      sectorContext: 'Consumer Discretionary (XLY) is down 7.3% YTD with TSLA as the worst performer at -18%. TSLA\'s 15% weight in XLY means sector outflows disproportionately hit the stock. The auto sub-sector (CARZ ETF) is down 12%.',
      riskFactors: [
        'Robotaxi announcement or FSD breakthrough could trigger a massive short squeeze',
        'Musk stepping back from government role would restore brand perception',
        'Q1 deliveries beating the lowered estimates could cause a relief rally',
      ],
    },
  },
  {
    id: 'S3',
    ticker: 'IWM',
    name: 'iShares Russell 2000 ETF',
    asset: 'equity',
    strategy: 'macro',
    entryLow: 198,
    entryHigh: 205,
    target: 182,
    stopLoss: 212,
    rsi: 40.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'Small caps are the most rate-sensitive equity cohort. With 40% of Russell 2000 debt floating-rate, every Fed hold at restrictive levels increases interest expense. Earnings recession underway — Russell 2000 earnings are projected to decline 3% in Q1.',
    catalyst: 'Fed rate decision Apr 30, regional bank earnings, high-yield credit spreads',
    dataPacket: {
      historicalContext: 'IWM has underperformed SPY by 14% over the past 12 months — the widest large/small divergence since 2000. When the spread gets this wide, small caps have historically mean-reverted, BUT that requires rate cuts or an un-inverted yield curve. Neither is imminent.',
      bondCorrelation: 'IWM has the highest sensitivity to the Fed Funds Rate of any major equity ETF (correlation: -0.72). The 40% floating-rate debt profile means small caps are paying ~8.5% average interest rates vs 4.2% for the S&P 500. This creates a fundamental earnings headwind that persists as long as rates are restrictive.',
      globalMacro: 'US economic surprise index has turned negative for the first time in 6 months, which historically hits small caps 2x harder than large caps. The NFIB Small Business Optimism Index dropped to 88.4 — its lowest reading since 2013. Small caps are 92% domestic revenue, so they get no benefit from USD weakness or global growth.',
      newsDrivers: [
        'Fed dot plot showed zero rate cuts in 2026 — crushing small cap rate sensitivity thesis',
        'High-yield credit spreads widened to 420bps from 320bps in January — stress signal',
        'Russell 2000 companies with negative earnings rose to 42% of the index from 35%',
        'Institutional flows out of IWM: $2.8B in March — largest monthly outflow since 2022',
      ],
      technicalLevels: {
        support: [195, 185, 175],
        resistance: [205, 212, 220],
        pivotPoints: { r1: 204, r2: 211, s1: 196, s2: 188 },
        movingAverages: { ma20: 200, ma50: 208, ma200: 215 },
      },
      sectorContext: 'Small cap value (IWN) is outperforming small cap growth (IWO) by 500bps, indicating a flight to quality even within the small cap space. The weakest subsectors are biotech, regional banks, and consumer discretionary.',
      riskFactors: [
        'Surprise Fed pivot to dovish stance would trigger explosive short squeeze in small caps',
        'Fiscal stimulus package targeting small business lending',
        'Extreme pessimism positioning (sentiment contrarian signal)',
      ],
    },
  },
  {
    id: 'S4',
    ticker: 'TLT',
    name: 'iShares 20+ Year Treasury Bond ETF',
    asset: 'bond',
    strategy: 'macro',
    entryLow: 88,
    entryHigh: 92,
    target: 82,
    stopLoss: 95,
    rsi: 42.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'Long-end rates have room to rise further. The term premium is being repriced higher as fiscal deficits widen ($1.8T projected for FY2026). Japan\'s YCC exit is flooding the global bond market with supply. Short TLT captures this structural shift.',
    catalyst: 'Treasury refunding announcement, BoJ meeting Apr 28, CPI data Apr 10',
    dataPacket: {
      historicalContext: 'TLT has declined 45% from its 2020 highs and shows no sign of bottoming. The 30Y yield at 4.9% is approaching the psychologically significant 5% level. Bond bear markets historically last 20-30 years — we are only 5 years into this cycle.',
      bondCorrelation: 'This IS the bond trade. TLT has a duration of 17 years, meaning every 100bps rise in the 30Y yield produces a ~17% decline in TLT. The fiscal trajectory (CBO projects $2T deficits by 2030) ensures persistent supply pressure. Foreign holdings of US Treasuries as a % of total have declined from 34% to 23%.',
      globalMacro: 'Japan\'s BoJ is normalizing policy — the 10Y JGB yield rose from 0.4% to 1.8% in 12 months. Japanese investors hold $1.1T in US Treasuries and are repatriating as domestic yields become attractive. This "reverse carry trade" is the single largest structural headwind for long-duration US bonds. The BoJ meeting April 28 could accelerate this if they hike again.',
      newsDrivers: [
        'US fiscal deficit tracking $1.8T for FY2026 — $300B worse than CBO projected',
        'BoJ Governor Ueda signaled "further normalization" at March press conference',
        'China reduced Treasury holdings for 8th consecutive month — now below $800B',
        'Treasury announcing increased auction sizes for May — more supply = lower prices',
      ],
      technicalLevels: {
        support: [85, 82, 78],
        resistance: [92, 95, 98],
        pivotPoints: { r1: 91, r2: 94, s1: 86, s2: 83 },
        movingAverages: { ma20: 89, ma50: 91, ma200: 93 },
      },
      sectorContext: 'The entire bond complex is under pressure — investment grade (LQD) down 4%, high yield (HYG) down 6%, munis (MUB) down 3% YTD. Duration is the common factor — the longer the maturity, the worse the performance.',
      riskFactors: [
        'Flight-to-safety rally during equity crash would spike TLT 5-8% in days',
        'Fed emergency rate cut would steepen curve and boost long bonds',
        'Recession confirmation would trigger massive bond buying',
      ],
    },
  },
  {
    id: 'S5',
    ticker: 'ARKK',
    name: 'ARK Innovation ETF',
    asset: 'equity',
    strategy: 'momentum',
    entryLow: 42,
    entryHigh: 45,
    target: 35,
    stopLoss: 48,
    rsi: 36.0,
    risk: 'HIGH',
    timeframe: '4-day',
    thesis: 'The poster child for speculative growth is in a persistent downtrend. ARKK is essentially a leveraged bet on declining rate expectations — and rates are staying higher for longer. Cathie Wood\'s top holdings (TSLA, COIN, ROKU) are all in downtrends with deteriorating fundamentals.',
    catalyst: 'Fed messaging, speculative tech earnings, risk sentiment shift',
    dataPacket: {
      historicalContext: 'ARKK is down 75% from its February 2021 peak and has never sustained a rally longer than 3 weeks during this decline. The ETF has experienced net outflows of $12B since its peak. The average cost basis of remaining holders is estimated at $75 — meaning most holders are underwater.',
      bondCorrelation: 'ARKK has the highest duration sensitivity of any equity ETF — its implied duration is estimated at 25+ years based on the cash flow profiles of its holdings. Correlation to the 10Y is -0.82. In a "higher for longer" rate regime, ARKK is structurally impaired.',
      globalMacro: 'The "growth at any price" regime ended in 2022 and has not returned. Speculative growth companies in ARKK are burning cash and facing tightening credit conditions. Venture capital funding down 40% from peak means the private-to-public pipeline that fed ARKK\'s thesis is broken.',
      newsDrivers: [
        'ARKK biggest holdings: TSLA (10%), COIN (9.5%), ROKU (7%) — all in downtrends',
        'Cathie Wood sold $200M of NVDA before the AI rally — highlighting poor market timing',
        'Fund redemptions accelerated to $800M in March from $400M in February',
        'ARK total AUM declined to $8B from peak of $50B — structural liquidity concerns',
      ],
      technicalLevels: {
        support: [38, 35, 30],
        resistance: [45, 48, 52],
        pivotPoints: { r1: 44, r2: 47, s1: 39, s2: 36 },
        movingAverages: { ma20: 43, ma50: 46, ma200: 48 },
      },
      sectorContext: 'Speculative tech basket (Goldman\'s non-profitable tech index) is down 22% YTD vs Nasdaq -9%. The divergence confirms that profitability is being rewarded while speculation is being punished.',
      riskFactors: [
        'Speculative mania revival (meme stock-style squeeze) could spike ARKK 20%+',
        'Fed dovish pivot would dramatically boost duration-sensitive names',
        'TSLA robotaxi catalyst could lift ARKK\'s largest holding 30%+',
      ],
    },
  },
  {
    id: 'S6',
    ticker: 'XLU',
    name: 'Utilities Select SPDR',
    asset: 'equity',
    strategy: 'relative-value',
    entryLow: 70,
    entryHigh: 72,
    target: 64,
    stopLoss: 75,
    rsi: 55.0,
    risk: 'LOW',
    timeframe: '4-day',
    thesis: 'Utilities are bond proxies that suffer in rising rate environments. With the 10Y pushing toward 5%, the dividend yield on XLU (3.1%) is increasingly uncompetitive vs risk-free rates. Regulatory lag means utilities can\'t pass through costs fast enough.',
    catalyst: 'Bond yield trajectory, Fed messaging, state rate case decisions',
    dataPacket: {
      historicalContext: 'XLU has underperformed SPX by 400bps when the 10Y yield is above 4.5% (current: 4.8%). The sector\'s P/E premium to the market has compressed from 5% to -8% over the past year. Utility dividend yields below the 2Y Treasury rate (5.0%) create a "why bother" dynamic for income investors.',
      bondCorrelation: 'XLU has the highest positive correlation to TLT (+0.78) of any equity sector — it is essentially a leveraged bond position with operational risk. When bond yields rise, XLU faces a double hit: higher borrowing costs AND multiple compression from competing income alternatives.',
      globalMacro: 'Rising interest rates increase the cost of capital for utility capex programs. US utilities have $400B in infrastructure spending planned through 2030, mostly debt-financed. Higher rates make these projects less accretive to earnings.',
      newsDrivers: [
        'Southern Company\'s nuclear project cost overrun reached $17B — 2x original estimate',
        'State regulators in Ohio and Texas denied rate increase requests for 2 utilities',
        'Utility bond issuance costs rose 80bps in Q1, pressuring forward earnings estimates',
        'Renewable energy PPA prices declining — compressing margins for utility-scale solar',
      ],
      technicalLevels: {
        support: [68, 64, 60],
        resistance: [72, 75, 78],
        pivotPoints: { r1: 71.5, r2: 74, s1: 68.5, s2: 65.5 },
        movingAverages: { ma20: 70.5, ma50: 72, ma200: 74 },
      },
      sectorContext: 'Utilities are the second-worst performing sector YTD behind real estate. The traditional "flight to safety" into utilities has not materialized this cycle because bond yields offer better risk-adjusted income.',
      riskFactors: [
        'Sharp bond rally would lift XLU significantly as a bond proxy',
        'AI data center power demand creating a new growth narrative for utilities',
        'Extreme defensive positioning during equity selloff could bid utilities up',
      ],
    },
  },
  {
    id: 'S7',
    ticker: 'XLRE',
    name: 'Real Estate Select SPDR',
    asset: 'equity',
    strategy: 'macro',
    entryLow: 38,
    entryHigh: 40,
    target: 34,
    stopLoss: 42,
    rsi: 33.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'Commercial real estate is in a secular downturn. Office vacancy at 20% nationally (highest ever), rising cap rates compressing valuations, and $680B in CRE debt maturing in 2026 at refinancing rates 300bps higher than origination. REITs are a direct play on this pain.',
    catalyst: 'Bank earnings CRE disclosures, CMBS delinquency data, property appraisal downgrades',
    dataPacket: {
      historicalContext: 'XLRE has underperformed SPX by 22% over 2 years. The sector is trading at a 30% discount to net asset value — but NAV itself is declining as properties are reappraised lower. Office REITs specifically are down 45% from 2022 peaks.',
      bondCorrelation: 'XLRE has a -0.65 correlation with the 10Y yield. Rising cap rates (currently 6.5% for office, up from 4.5% in 2022) directly reduce property values. The refinancing cliff means many properties will face negative equity when debt matures at current rates.',
      globalMacro: 'Remote work adoption has stabilized at 30% of workdays — permanently reducing office demand. China\'s property crisis demonstrates how CRE downturns can become self-reinforcing. European REIT markets are already in recession, with UK commercial property values down 25% from peak.',
      newsDrivers: [
        'CMBS delinquency rate rose to 5.8% — highest since 2014',
        'Brookfield defaulted on $2.3B office portfolio in LA — high-profile signal of distress',
        'Office vacancy hit 20.1% nationally per CBRE — surpassing the GFC peak',
        'Morgan Stanley estimates $500B in CRE losses are still unrealized in bank portfolios',
      ],
      technicalLevels: {
        support: [36, 34, 31],
        resistance: [40, 42, 44],
        pivotPoints: { r1: 39.5, r2: 41.5, s1: 36.5, s2: 34.5 },
        movingAverages: { ma20: 38.5, ma50: 40.2, ma200: 42.8 },
      },
      sectorContext: 'Real estate is the worst-performing SPX sector over 2 years. Data center REITs are the only subsector showing strength, but they represent only 12% of XLRE. The breadth of weakness across office, retail, and multifamily drives the trade.',
      riskFactors: [
        'Fed rate cuts would provide massive relief to CRE valuations',
        'Government intervention (CRE bailout program) risk',
        'Data center REIT rally could lift the overall sector',
      ],
    },
  },
  {
    id: 'S8',
    ticker: 'FXI',
    name: 'iShares China Large-Cap ETF',
    asset: 'equity',
    strategy: 'macro',
    entryLow: 28,
    entryHigh: 30,
    target: 24,
    stopLoss: 32,
    rsi: 42.0,
    risk: 'HIGH',
    timeframe: '4-day',
    thesis: 'China stimulus is underwhelming relative to market expectations. Property crisis deepening with tier-2 and tier-3 city prices still falling. Deflation persisting at -0.3% CPI. Capital outflows accelerating as foreign investors reduce China allocation.',
    catalyst: 'PMI data, property sales data, tariff escalation risk, PBOC policy',
    dataPacket: {
      historicalContext: 'FXI has been in a downtrend since 2021, falling 55% from the peak. Each stimulus announcement has produced shorter and shallower rallies — a classic bear market pattern. The "China trade" has become a consensus short among global macro funds.',
      bondCorrelation: 'Chinese government bonds are diverging from US Treasuries — the yield spread has narrowed from 280bps (China premium) to -120bps (US premium). This yield inversion is driving capital out of China and into USD assets. The correlation between FXI and the US 10Y is -0.25.',
      globalMacro: 'China\'s property sector represents 30% of GDP including related industries. Tier-1 city prices stabilized but tier-2/3 continue to fall 5-10% annually. Youth unemployment at 16.5%. Deflationary spiral risk as consumers defer spending. China\'s working-age population peaked in 2022 and is now declining — a structural headwind.',
      newsDrivers: [
        'China March PMI disappointed at 49.5 — back in contraction territory',
        'Property developer Vanke missed a bond payment — third major developer in distress this year',
        'Foreign direct investment in China fell 28% YoY — worst reading in 20 years',
        'Trump threatened additional 25% tariffs on Chinese goods if trade deficit doesn\'t narrow',
      ],
      technicalLevels: {
        support: [26, 24, 21],
        resistance: [30, 32, 35],
        pivotPoints: { r1: 29.5, r2: 31.5, s1: 26.5, s2: 24.5 },
        movingAverages: { ma20: 28.5, ma50: 30, ma200: 31.5 },
      },
      sectorContext: 'Emerging market equities (EEM) are underperforming developed markets (EFA) by 800bps YTD, with China representing 30% of EM indices. Excluding China, EM would be flat — China is the primary drag.',
      riskFactors: [
        'Massive "bazooka" stimulus package could trigger 15-20% short squeeze',
        'US-China trade deal reducing tariff fears',
        'Technical oversold bounce from extreme positioning',
      ],
    },
  },
  {
    id: 'S9',
    ticker: 'BYND',
    name: 'Beyond Meat',
    asset: 'equity',
    strategy: 'momentum',
    entryLow: 5.5,
    entryHigh: 6.5,
    target: 3.5,
    stopLoss: 7.5,
    rsi: 40.0,
    risk: 'HIGH',
    timeframe: '4-day',
    thesis: 'Plant-based meat category in secular decline. Revenue falling 25% YoY with no path to profitability. Cash burn rate implies potential bankruptcy within 18 months without capital raise. The stock is a zero candidate.',
    catalyst: 'Q1 earnings, cash flow report, potential going concern warning',
    dataPacket: {
      historicalContext: 'BYND is down 97% from its 2019 IPO peak of $234. Revenue has declined for 8 consecutive quarters. The company has $1.1B in debt with only $180M cash — and is burning $50M/quarter. No analyst has a Buy rating.',
      bondCorrelation: 'BYND\'s bond trades at 45 cents on the dollar — implying a 35% probability of default. The stock is essentially an equity option on a restructuring. High-yield credit spread widening accelerates the funding cost and makes refinancing increasingly impossible.',
      globalMacro: 'Consumer trend shift away from plant-based meat is global. McDonald\'s ended McPlant trials. Grocery channel data shows plant-based meat category declined 12% in 2025 vs 2% decline for overall protein. The "sustainability premium" that consumers were willing to pay has evaporated.',
      newsDrivers: [
        'McDonald\'s permanently removed Beyond Meat products from US menus',
        'BYND cut 19% of workforce in March — third round of layoffs in 18 months',
        'Short interest at 37% of float — the highest of any consumer stock',
        'Debt covenant waiver obtained in February — signaling financial stress',
      ],
      technicalLevels: {
        support: [4.5, 3.5, 2.0],
        resistance: [6.5, 8.0, 10.0],
        pivotPoints: { r1: 6.2, r2: 7.5, s1: 4.8, s2: 3.8 },
        movingAverages: { ma20: 5.8, ma50: 6.5, ma200: 8.2 },
      },
      sectorContext: 'Consumer staples (XLP) is relatively stable but plant-based is the worst-performing subsector. Impossible Foods (private) has also slashed valuations, confirming category-wide distress.',
      riskFactors: [
        'Short squeeze (37% short interest means any positive catalyst triggers violent covering)',
        'Acquisition by strategic buyer (unlikely but non-zero probability)',
        'Viral social media moment driving retail buying frenzy',
      ],
    },
  },
  {
    id: 'S10',
    ticker: 'DIS',
    name: 'Walt Disney Co',
    asset: 'equity',
    strategy: 'relative-value',
    entryLow: 95,
    entryHigh: 100,
    target: 82,
    stopLoss: 106,
    rsi: 37.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'Disney+ subscriber growth stalled. Linear TV revenue declining 8% annually. Theme parks showing softening demand with per-capita spending declining for the first time since 2020. The sum-of-parts valuation thesis has not materialized.',
    catalyst: 'Q2 earnings, streaming profitability update, ESPN standalone launch timeline',
    dataPacket: {
      historicalContext: 'DIS has been range-bound between $80-110 for 2 years with no discernible uptrend. The stock trades at a 40% discount to its pandemic peak. Disney+ has lost $13B cumulative — more than any streaming service in history. Parks EBITDA growth has decelerated from 25% to 4%.',
      bondCorrelation: 'DIS is moderately rate-sensitive (correlation to 10Y: -0.32) due to its capital-intensive business model ($6B/year in capex). Higher rates increase the cost of theme park expansion and content production financing.',
      globalMacro: 'Consumer discretionary spending is slowing globally. Theme park attendance in Shanghai and Paris showing weakness due to local economic conditions. The strong USD reduces international revenue when translated back. Cord-cutting accelerating at 6% annually destroys the ESPN cable bundle economics.',
      newsDrivers: [
        'Disney+ subscriber count flat at 152M — missed analyst estimate of 158M',
        'Theme park wait times down 20% YoY — indicating softer demand',
        'ESPN deal with Penn National generating less revenue than projected',
        'Activist investor Nelson Peltz exited his position, removing the catalyst for corporate action',
      ],
      technicalLevels: {
        support: [90, 82, 75],
        resistance: [100, 108, 115],
        pivotPoints: { r1: 99, r2: 106, s1: 91, s2: 84 },
        movingAverages: { ma20: 96, ma50: 100, ma200: 105 },
      },
      sectorContext: 'Media/entertainment subsector is underperforming XLC by 600bps. Netflix is taking streaming share while Disney+ stagnates. The Comcast/NBCU spinoff is creating a new competitor.',
      riskFactors: [
        'ESPN standalone streaming launch could reignite growth narrative',
        'IP monetization breakthrough (new Avengers, Star Wars content cycle)',
        'Strategic asset sale (ABC, linear TV) to unlock value',
      ],
    },
  },
  {
    id: 'S11',
    ticker: 'NKE',
    name: 'Nike Inc',
    asset: 'equity',
    strategy: 'momentum',
    entryLow: 72,
    entryHigh: 76,
    target: 62,
    stopLoss: 80,
    rsi: 34.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'Nike is losing market share to On Running, Hoka, and New Balance across every category. DTC strategy has alienated wholesale partners. China recovery thesis has failed to materialize. Inventory levels still elevated at 18% above normalized levels.',
    catalyst: 'Q4 earnings June, wholesale partner order data, China Singles Day comparisons',
    dataPacket: {
      historicalContext: 'NKE is down 35% from 2021 highs and making lower lows each quarter. Revenue growth has decelerated from 10% to 1% YoY. The stock\'s P/E premium to consumer discretionary peers has compressed from 30% to 5% as the growth premium evaporates.',
      bondCorrelation: 'NKE has moderate rate sensitivity (correlation to 10Y: -0.28) but the primary driver is consumer spending, not rates. Consumer confidence surveys at 2-year lows are the more relevant macro input.',
      globalMacro: 'Global athletic footwear market is growing 5% but Nike is losing 200bps of share annually to challengers. China (17% of revenue) consumer confidence at 15-year lows. European demand softening as inflation erodes purchasing power.',
      newsDrivers: [
        'On Holdings (ONON) reported 28% revenue growth — taking share directly from Nike',
        'Nike CFO warned of "reset year" for revenue growth at investor day',
        'Foot Locker reduced Nike allocation by 15% in favor of New Balance and Hoka',
        'China revenue declined 5% in Q3 — the fourth consecutive quarter of decline',
      ],
      technicalLevels: {
        support: [68, 62, 55],
        resistance: [76, 82, 88],
        pivotPoints: { r1: 75, r2: 80, s1: 69, s2: 64 },
        movingAverages: { ma20: 73, ma50: 78, ma200: 85 },
      },
      sectorContext: 'Athletic/footwear subsector is diverging — ON +45% YTD, DECK +22%, while NKE -12%. The market is pricing a permanent share loss, not a cyclical dip.',
      riskFactors: [
        'New CEO turnaround strategy could restore investor confidence',
        'Olympics-year marketing boost (though 2026 is not an Olympic year)',
        'China stimulus driving consumer spending recovery',
      ],
    },
  },
  {
    id: 'S12',
    ticker: 'COIN',
    name: 'Coinbase Global',
    asset: 'equity',
    strategy: 'macro',
    entryLow: 195,
    entryHigh: 210,
    target: 160,
    stopLoss: 225,
    rsi: 38.0,
    risk: 'HIGH',
    timeframe: '4-day',
    thesis: 'Crypto trading volumes declining 30% from January peak. Fee compression from competitive pressure. Regulatory overhang from SEC. Revenue is almost entirely transaction-based — a bear market in crypto directly translates to revenue collapse.',
    catalyst: 'BTC price action, SEC regulatory decisions, Q1 earnings',
    dataPacket: {
      historicalContext: 'COIN has a 0.92 beta to Bitcoin — it is essentially leveraged BTC exposure with operational risk. Trading revenue (70% of total) fell 35% QoQ in Q4 2025. The stock has failed to hold above $220 on three separate occasions in 2026.',
      bondCorrelation: 'COIN is among the most rate-sensitive stocks (-0.65 correlation to 10Y) because crypto is the ultimate long-duration asset. Rising rates reduce the speculative capital available for crypto trading, directly impacting COIN\'s transaction revenue.',
      globalMacro: 'Crypto regulation globally is tightening — EU MiCA is increasing compliance costs, US SEC enforcement actions continue. The "regulatory clarity" bull thesis has not materialized into an earnings catalyst. Institutional trading volumes are migrating to lower-cost venues.',
      newsDrivers: [
        'Crypto trading volumes in March declined 28% from January highs',
        'SEC filed additional enforcement action against Coinbase for listing unregistered securities',
        'Binance regained global market share after compliance restructuring — competitive pressure',
        'Coinbase subscription revenue growth slowed to 8% from 22% — diversification thesis weakening',
      ],
      technicalLevels: {
        support: [180, 160, 140],
        resistance: [210, 225, 250],
        pivotPoints: { r1: 208, r2: 222, s1: 185, s2: 168 },
        movingAverages: { ma20: 200, ma50: 215, ma200: 195 },
      },
      sectorContext: 'Crypto-related stocks (MSTR, MARA, RIOT) are all in downtrends. The sector correlation to BTC price means any crypto weakness ripples through the entire basket.',
      riskFactors: [
        'Bitcoin breakout above $90K would squeeze shorts across all crypto equities',
        'SEC dropping enforcement action would remove the regulatory discount',
        'Base revenue (subscriptions) growing faster than expected could change the narrative',
      ],
    },
  },
]

// ============================================================================
// FOREX TRADE IDEAS (8 Ideas)
// ============================================================================
export const FOREX_IDEAS = [
  {
    id: 'FX1',
    ticker: 'USDJPY',
    name: 'USD/JPY',
    asset: 'forex',
    strategy: 'carry',
    direction: 'short',
    entryLow: 153.0,
    entryHigh: 155.0,
    target: 145.0,
    stopLoss: 158.0,
    rsi: 68.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'BoJ policy normalization is the defining macro trade of 2026. Japan exiting negative rates and reducing YCC tolerance band is narrowing the US-Japan yield differential. The carry trade unwind (estimated $2T+ in yen-funded positions) creates massive yen buying pressure.',
    catalyst: 'BoJ meeting Apr 28, US-Japan yield spread compression, intervention risk above 155',
    dataPacket: {
      historicalContext: 'USD/JPY has declined from 162 to 153 since January as the BoJ normalization thesis plays out. The 200-day MA at 148 is the medium-term target. Japan intervened at 160 in 2024 and at 152 in 2022 — the MoF has demonstrated willingness to sell USD/JPY when moves become disorderly.',
      bondCorrelation: 'USD/JPY has a +0.85 correlation with the US-Japan 10Y spread, which has narrowed from 380bps to 300bps in 2026. Every 50bps of additional narrowing historically moves USD/JPY 5-7 figures lower. JGB yields rising faster than US yields creates the tailwind.',
      globalMacro: 'Japan\'s Q4 GDP surprised to the upside (+2.2% annualized), supporting the case for further BoJ tightening. Tokyo CPI at 3.2% — well above the 2% target — gives the BoJ cover to hike. Japan\'s current account surplus of $180B/year creates structural yen demand. The carry trade unwind is analogous to 2007-2008, when USD/JPY fell from 124 to 87.',
      newsDrivers: [
        'BoJ Governor Ueda: "We will continue to adjust policy based on incoming data" — hawkish interpretation',
        'Japan Finance Minister warned of "excessive currency moves" above 155 — verbal intervention',
        'Japanese life insurers reducing USD bond hedging — bringing yen flows home',
        'US-Japan 10Y spread at narrowest since 2023 — directional confirmation',
      ],
      technicalLevels: {
        support: [150, 148, 145],
        resistance: [155, 158, 162],
        pivotPoints: { r1: 154.5, r2: 157, s1: 151, s2: 148.5 },
        movingAverages: { ma20: 152.5, ma50: 155, ma200: 148 },
      },
      sectorContext: 'JPY is the strongest G10 currency YTD (+4% vs USD). AUD/JPY and EUR/JPY crosses are also declining, confirming yen strength is broad-based, not just a USD story.',
      riskFactors: [
        'Fed hawkish surprise widening the yield differential',
        'BoJ backing away from normalization due to global growth fears',
        'Risk-on rally reviving carry trade flows into higher-yielding currencies',
      ],
    },
  },
  {
    id: 'FX2',
    ticker: 'EURUSD',
    name: 'EUR/USD',
    asset: 'forex',
    strategy: 'mean-reversion',
    direction: 'long',
    entryLow: 1.075,
    entryHigh: 1.085,
    target: 1.115,
    stopLoss: 1.060,
    rsi: 42.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'EUR/USD is oversold relative to rate differentials. The ECB has paused cuts while the Fed is being pushed to cut by slowing US data. The narrowing ECB-Fed rate gap supports euro appreciation. European defense spending is a new source of capital inflow.',
    catalyst: 'ECB meeting, US employment data, European defense spending announcements',
    dataPacket: {
      historicalContext: 'EUR/USD has been range-bound between 1.05-1.12 for 18 months. Current level at 1.08 is near the middle, but positioning is extremely USD-long. CFTC data shows net USD longs at 2-year highs — a potential crowded trade.',
      bondCorrelation: 'EUR/USD has a -0.72 correlation with the US-German 10Y spread. The spread has narrowed from 200bps to 170bps as ECB pauses and Bund yields rise on defense spending expectations. Further narrowing to 140bps would push EUR/USD to 1.10-1.12.',
      globalMacro: 'Germany\'s €100B defense fund and relaxation of debt brake rules represent a fiscal paradigm shift that is euro-positive. The EU\'s €800B reconstruction and defense package, funded by joint issuance, creates structural demand for euros. Meanwhile, US twin deficits (fiscal + trade) continue to erode long-term USD fundamentals.',
      newsDrivers: [
        'ECB President Lagarde: "We see no urgency for further rate adjustments" — hawkish pause',
        'German Bund yields rose to 2.8% — highest since 2011 on defense spending',
        'CFTC: Net USD longs at $34B — most crowded positioning in 24 months',
        'Eurozone PMI composite at 50.4 — showing stabilization vs prior contraction',
      ],
      technicalLevels: {
        support: [1.075, 1.060, 1.045],
        resistance: [1.095, 1.110, 1.125],
        pivotPoints: { r1: 1.090, r2: 1.105, s1: 1.072, s2: 1.058 },
        movingAverages: { ma20: 1.082, ma50: 1.078, ma200: 1.090 },
      },
      sectorContext: 'EUR is the second-strongest G10 currency behind JPY in April. EUR/CHF is stable, confirming euro-specific strength rather than CHF weakness.',
      riskFactors: [
        'US exceptionalism narrative returning on strong data',
        'European energy crisis resurgence (Russia pipeline disruption)',
        'ECB surprise cut reversing the rate convergence thesis',
      ],
    },
  },
  {
    id: 'FX3',
    ticker: 'GBPUSD',
    name: 'GBP/USD',
    asset: 'forex',
    strategy: 'carry',
    direction: 'long',
    entryLow: 1.285,
    entryHigh: 1.295,
    target: 1.325,
    stopLoss: 1.270,
    rsi: 50.0,
    risk: 'LOW',
    timeframe: '4-day',
    thesis: 'UK rates at 5.0% are the highest in the G7. BoE is the most hawkish major central bank due to persistent services inflation at 5.4%. The positive carry of 50bps vs USD makes long GBP/USD an income-generating position while waiting for appreciation.',
    catalyst: 'UK CPI data, BoE meeting, wage growth data',
    dataPacket: {
      historicalContext: 'GBP/USD has been trending higher since October 2025, making higher lows and higher highs. The pair is above its 50-day and 200-day MAs. The UK-US rate differential has been positive for 6 months — each month, carry income adds to the trade\'s profitability.',
      bondCorrelation: 'GBP/USD has a -0.55 correlation with the US-UK 10Y spread. With UK gilts yielding 4.7% vs US 10Y at 4.8%, the spread is the tightest in 18 months. If US yields fall (or UK rise), GBP/USD benefits.',
      globalMacro: 'UK services inflation at 5.4% is the stickiest in the G7, ensuring the BoE stays hawkish. UK labor market remains tight with unemployment at 4.0%. London financial services sector benefiting from EU regulatory complexity pushing business to the City. UK GDP growth of 1.8% is outpacing Eurozone (0.8%).',
      newsDrivers: [
        'BoE Chief Economist Pill: "We are not at the point where we can declare victory on inflation"',
        'UK wage growth at 5.8% — well above BoE\'s target, supporting hawkish stance',
        'London commercial real estate seeing foreign capital inflows at 3-year highs',
        'UK-India free trade agreement expected to boost GDP by 0.3% — positive catalyst',
      ],
      technicalLevels: {
        support: [1.285, 1.270, 1.255],
        resistance: [1.305, 1.320, 1.340],
        pivotPoints: { r1: 1.302, r2: 1.318, s1: 1.282, s2: 1.268 },
        movingAverages: { ma20: 1.292, ma50: 1.285, ma200: 1.275 },
      },
      sectorContext: 'GBP is the third-strongest G10 currency YTD. GBP/EUR is at 2-year highs, confirming relative UK economic outperformance.',
      riskFactors: [
        'UK recession scare triggering BoE to pivot dovish',
        'Political instability or fiscal concerns widening gilt spreads',
        'Global risk-off driving flows to USD as safe haven',
      ],
    },
  },
  {
    id: 'FX4',
    ticker: 'USDCHF',
    name: 'USD/CHF',
    asset: 'forex',
    strategy: 'macro',
    direction: 'short',
    entryLow: 0.885,
    entryHigh: 0.895,
    target: 0.855,
    stopLoss: 0.910,
    rsi: 55.0,
    risk: 'LOW',
    timeframe: '4-day',
    thesis: 'Swiss franc is the ultimate safe haven currency. With Iran escalation risk, equity volatility rising, and geopolitical uncertainty at multi-year highs, CHF demand increases structurally. SNB has shifted from fighting franc strength to tolerating it.',
    catalyst: 'Iran deadline Apr 6, VIX spike, SNB policy shift, geopolitical escalation',
    dataPacket: {
      historicalContext: 'USD/CHF has been in a secular downtrend for decades, reflecting Switzerland\'s current account surplus (12% of GDP) and the franc\'s safe haven status. The pair is below the 200-day MA and making lower highs. During the 2022 Ukraine escalation, CHF gained 5% in 30 days.',
      bondCorrelation: 'CHF typically strengthens when global bond volatility (MOVE index) rises. The MOVE index at 120 (vs 80 average) confirms elevated fixed income stress. Swiss government bonds are the only major sovereign market with negative real yields — investors pay for safety.',
      globalMacro: 'Switzerland\'s current account surplus of 12% of GDP creates structural demand for CHF. The SNB shifted its policy from "fighting franc appreciation" to "allowing the exchange rate to adjust," removing a key headwind. Swiss inflation at 1.2% is the lowest in the G7, supporting real return advantage.',
      newsDrivers: [
        'SNB Chairman Jordan: "We are comfortable with the current exchange rate level"',
        'Swiss gold imports surged 40% in February — reflecting global safe haven flows through Switzerland',
        'VIX at 22 — above the 18 threshold that historically triggers CHF buying',
        'Iran tensions boosting demand for Swiss-denominated assets as neutral safe haven',
      ],
      technicalLevels: {
        support: [0.870, 0.855, 0.840],
        resistance: [0.895, 0.910, 0.925],
        pivotPoints: { r1: 0.893, r2: 0.907, s1: 0.872, s2: 0.858 },
        movingAverages: { ma20: 0.888, ma50: 0.892, ma200: 0.900 },
      },
      sectorContext: 'CHF is strengthening across all crosses — EUR/CHF and GBP/CHF also declining, confirming broad-based franc demand rather than just USD weakness.',
      riskFactors: [
        'Risk-on rally reducing safe haven demand',
        'SNB intervening to weaken CHF if export sector suffers',
        'US exceptionalism driving USD strength overriding CHF flows',
      ],
    },
  },
  {
    id: 'FX5',
    ticker: 'AUDUSD',
    name: 'AUD/USD',
    asset: 'forex',
    strategy: 'macro',
    direction: 'short',
    entryLow: 0.655,
    entryHigh: 0.665,
    target: 0.625,
    stopLoss: 0.680,
    rsi: 40.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'AUD is a proxy for China growth and commodity demand. With China PMI back in contraction and iron ore prices declining, the fundamental supports for AUD are weakening. RBA has turned dovish, removing the rate support pillar.',
    catalyst: 'China PMI, iron ore prices, RBA meeting, commodity demand data',
    dataPacket: {
      historicalContext: 'AUD/USD has been trending lower since the January high of 0.685. The pair has a 0.78 correlation with iron ore prices, which have fallen 15% from recent highs. AUD is historically one of the first currencies to sell off during global growth scares.',
      bondCorrelation: 'AUD/USD has a -0.45 correlation with the US 10Y, but the more relevant relationship is the RBA-Fed rate differential. RBA cut rates to 4.1% in February while the Fed held at 5.25% — the widening gap is AUD-negative.',
      globalMacro: 'Australia\'s economy is slowing — GDP growth at 1.1% is the weakest since 2020 (excluding COVID). China\'s steel demand decline directly impacts Australian iron ore exports (60% of total exports). The housing market is cooling after RBA rate cuts, removing the wealth effect.',
      newsDrivers: [
        'Iron ore prices fell below $100/tonne — down from $130 in January',
        'RBA cut rates 25bps in February and signaled potential further easing',
        'China steel production declined 5% YoY — direct hit to Australian exports',
        'Australian consumer confidence at 3-year low per Westpac survey',
      ],
      technicalLevels: {
        support: [0.645, 0.625, 0.605],
        resistance: [0.665, 0.680, 0.695],
        pivotPoints: { r1: 0.662, r2: 0.678, s1: 0.648, s2: 0.632 },
        movingAverages: { ma20: 0.658, ma50: 0.665, ma200: 0.670 },
      },
      sectorContext: 'Commodity currencies (AUD, NZD, CAD) are all weakening vs USD. AUD/NZD cross is also declining, indicating AUD-specific weakness beyond broad commodity softness.',
      riskFactors: [
        'China mega-stimulus driving iron ore prices higher',
        'RBA hiking surprise on sticky inflation',
        'USD broad weakness overriding AUD fundamentals',
      ],
    },
  },
  {
    id: 'FX6',
    ticker: 'USDMXN',
    name: 'USD/MXN',
    asset: 'forex',
    strategy: 'carry',
    direction: 'short',
    entryLow: 17.2,
    entryHigh: 17.8,
    target: 16.2,
    stopLoss: 18.5,
    rsi: 52.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'Mexico\'s Banxico maintains rates at 10.75% — a 550bps premium to the Fed. This enormous carry makes short USD/MXN one of the highest-yielding trades in FX. Nearshoring trend driving record FDI into Mexico supports MXN structurally.',
    catalyst: 'Banxico meeting, nearshoring FDI data, remittance flows, US-Mexico trade data',
    dataPacket: {
      historicalContext: 'MXN has been the best-performing EM currency over 3 years (+28% vs USD). The carry of 550bps annualized means you earn approximately 1.5% per month simply from the rate differential. MXN has consistently mean-reverted after USD/MXN spikes above 17.5.',
      bondCorrelation: 'USD/MXN has a +0.55 correlation with US 10Y yields, but the carry advantage overwhelms rate moves. A 50bps rise in US yields costs approximately 1% on the MXN position — but 1 month of carry earns 1.5%. The math favors holding.',
      globalMacro: 'Mexico is the primary beneficiary of the US-China supply chain diversification. FDI into Mexico reached $36B in 2025 — a record. Tesla, BMW, and 40+ other manufacturers are building or expanding factories in Mexico. Remittances at $63B/year provide a structural floor for MXN demand.',
      newsDrivers: [
        'Banxico held rates at 10.75% — signaling patience despite global cutting cycle',
        'Tesla broke ground on Monterrey gigafactory — $5B investment creating MXN demand',
        'Mexico FDI in January reached $4.1B — highest January on record',
        'JP Morgan recommended MXN as top EM carry trade for Q2 2026',
      ],
      technicalLevels: {
        support: [16.8, 16.2, 15.5],
        resistance: [17.8, 18.5, 19.0],
        pivotPoints: { r1: 17.6, r2: 18.2, s1: 17.0, s2: 16.5 },
        movingAverages: { ma20: 17.3, ma50: 17.5, ma200: 17.0 },
      },
      sectorContext: 'EM FX is mixed, but MXN, BRL, and INR are outperforming due to carry advantages. MXN\'s carry-to-volatility ratio (Sharpe) is the highest in EM at 2.1.',
      riskFactors: [
        'US-Mexico trade policy disruption (tariff threats)',
        'EM risk-off event causing broad carry trade unwind',
        'Banxico surprise cut removing carry advantage',
      ],
    },
  },
  {
    id: 'FX7',
    ticker: 'EURGBP',
    name: 'EUR/GBP',
    asset: 'forex',
    strategy: 'momentum',
    direction: 'short',
    entryLow: 0.855,
    entryHigh: 0.862,
    target: 0.835,
    stopLoss: 0.872,
    rsi: 45.0,
    risk: 'LOW',
    timeframe: '4-day',
    thesis: 'ECB dovish relative to BoE creates a persistent rate differential favoring GBP. UK economic data outperforming eurozone. The EUR/GBP cross is in a clear downtrend with the 50-day MA acting as resistance.',
    catalyst: 'ECB vs BoE rate decisions, UK vs EU PMI divergence, trade balance data',
    dataPacket: {
      historicalContext: 'EUR/GBP has declined 4% from the October 2025 high of 0.89. The pair is below all key moving averages. When the ECB-BoE rate differential has been negative (as now, -75bps), EUR/GBP has averaged -3% over 6 months.',
      bondCorrelation: 'EUR/GBP is driven almost entirely by the UK-German 2Y yield spread. Gilts yielding 4.5% vs Bunds at 2.8% creates a 170bps advantage for sterling. This is the widest spread since 2008.',
      globalMacro: 'UK GDP growth (1.8%) is outpacing eurozone (0.8%) for the first time since Brexit. London is regaining financial services market share from Frankfurt and Paris. The UK\'s flexible labor market is adjusting faster to post-pandemic structural shifts.',
      newsDrivers: [
        'UK services PMI at 54.2 vs eurozone 50.1 — widest gap in 2 years',
        'BoE holding at 5.0% while ECB already cut to 4.25% — divergence accelerating',
        'UK wage growth at 5.8% keeps BoE hawkish — no cuts expected until H2 2026',
        'German IFO business climate index fell for 3rd consecutive month',
      ],
      technicalLevels: {
        support: [0.845, 0.835, 0.825],
        resistance: [0.862, 0.872, 0.882],
        pivotPoints: { r1: 0.860, r2: 0.870, s1: 0.847, s2: 0.838 },
        movingAverages: { ma20: 0.855, ma50: 0.862, ma200: 0.868 },
      },
      sectorContext: 'GBP is outperforming EUR against all G10 currencies. EUR/GBP, EUR/CHF, and EUR/JPY all declining confirms broad EUR weakness.',
      riskFactors: [
        'UK economic shock (recession data) closing the growth gap',
        'ECB hawkish surprise on sticky eurozone inflation',
        'Brexit-related trade disruption headlines',
      ],
    },
  },
  {
    id: 'FX8',
    ticker: 'NZDUSD',
    name: 'NZD/USD',
    asset: 'forex',
    strategy: 'mean-reversion',
    direction: 'short',
    entryLow: 0.598,
    entryHigh: 0.608,
    target: 0.572,
    stopLoss: 0.618,
    rsi: 38.0,
    risk: 'MEDIUM',
    timeframe: '4-day',
    thesis: 'New Zealand\'s economy is in recession with 2 consecutive quarters of negative GDP growth. RBNZ has cut rates aggressively to 3.75% from 5.5%. The dairy sector (NZ\'s primary export) facing price declines. NZD is the weakest G10 currency.',
    catalyst: 'RBNZ meeting, dairy auction prices, GDP data, employment report',
    dataPacket: {
      historicalContext: 'NZD/USD has fallen 12% from the September 2025 high of 0.68. The pair is well below its 200-day MA at 0.625 — a strong bearish signal. New Zealand\'s current account deficit of 7.5% of GDP is the worst in the OECD, creating structural NZD selling pressure.',
      bondCorrelation: 'NZD is highly sensitive to global risk appetite (correlation to VIX: -0.55). As a small, open, commodity-dependent economy, NZ is disproportionately affected by global growth scares. The NZ-US 2Y yield spread at -150bps is the widest in 5 years.',
      globalMacro: 'New Zealand is in a technical recession — GDP contracted -0.3% in Q3 and -0.2% in Q4 2025. Housing prices have declined 8% from peak, creating a negative wealth effect. Immigration, which had supported growth, has turned negative as workers leave for Australia. Dairy prices (GDT index) down 15% from 2025 highs.',
      newsDrivers: [
        'RBNZ cut rates 50bps in March — most aggressive easing in the G10',
        'NZ unemployment rose to 5.2% — highest since 2020',
        'Dairy auction prices fell 8% at latest fortnightly sale',
        'ANZ Business Confidence survey at -52 — worst reading since 2008',
      ],
      technicalLevels: {
        support: [0.590, 0.572, 0.555],
        resistance: [0.608, 0.620, 0.635],
        pivotPoints: { r1: 0.605, r2: 0.618, s1: 0.592, s2: 0.578 },
        movingAverages: { ma20: 0.600, ma50: 0.612, ma200: 0.625 },
      },
      sectorContext: 'NZD is underperforming even within commodity currencies. AUD/NZD is rising, confirming NZD-specific weakness beyond the commodity complex.',
      riskFactors: [
        'Global dairy price recovery on China restocking',
        'RBNZ pausing cuts if inflation rebounds',
        'Broad USD weakness overriding NZD fundamentals',
      ],
    },
  },
]

// ============================================================================
// RISK EVENTS
// ============================================================================
export const RISK_EVENTS = [
  { date: 'Apr 6', event: 'Trump Iran Deadline', impact: 'Oil, Equities, VIX, Gold, JPY', volatility: 'EXTREME', action: 'Size positions at 50% max. Hedge with gold longs and VIX calls.' },
  { date: 'Apr 10', event: 'US CPI Release', impact: 'Treasuries, USD, Equities, Gold', volatility: 'HIGH', action: 'Reduce duration exposure. Watch for hot print driving USD strength.' },
  { date: 'Apr 11', event: 'JPM Earnings (Bank Season Opens)', impact: 'XLF, Financials, Credit', volatility: 'HIGH', action: 'Watch credit quality commentary. CRE reserves key focus.' },
  { date: 'Apr 16', event: 'Fed Beige Book', impact: 'Treasuries, USD, SPX', volatility: 'MEDIUM', action: 'Monitor for growth signals and labor market commentary.' },
  { date: 'Apr 22', event: 'RTX + LMT Earnings', impact: 'Defense sector, ITA', volatility: 'MEDIUM', action: 'Defense order intake and backlog growth key metrics.' },
  { date: 'Apr 24', event: 'CAT Earnings', impact: 'Industrials, XLI', volatility: 'MEDIUM', action: 'Equipment demand and dealer inventory data critical.' },
  { date: 'Apr 25', event: 'XOM Earnings', impact: 'Energy, XLE, Oil', volatility: 'HIGH', action: 'Production guidance and capital allocation commentary.' },
  { date: 'Apr 28', event: 'BoJ Policy Meeting', impact: 'JGB, JPY, USD/JPY, Carry Trades', volatility: 'HIGH', action: 'Watch for rate hike and YCC adjustment. Critical for JPY trades.' },
  { date: 'Apr 29', event: 'MSFT Earnings', impact: 'Tech sector, Nasdaq, AI theme', volatility: 'HIGH', action: 'Azure growth rate and AI revenue disclosure key focus.' },
  { date: 'Apr 30', event: 'Fed Rate Decision', impact: 'All risk assets', volatility: 'EXTREME', action: 'Flatten risk into meeting. Dot plot revision critical for rates outlook.' },
]

// ============================================================================
// SCENARIO ANALYSIS
// ============================================================================
export const SCENARIOS = [
  {
    name: 'Ceasefire / Withdrawal',
    probability: 35,
    impacts: { oil: '-20-30%', spx: '+5-8%', vix: '-40%', energy: '-15-20%', tech: '+8-12%', defense: '-5-8%', gold: '-3-5%', usdjpy: '+3-5%' },
    bestPosition: 'Long Tech, Short Energy, Short Gold',
  },
  {
    name: 'Status Quo / Stalemate',
    probability: 40,
    impacts: { oil: '±5%', spx: '±2%', vix: 'Flat', energy: '±3%', tech: '±2%', defense: '+2-3%', gold: '+1-2%', usdjpy: '±1%' },
    bestPosition: 'Hold current mix, harvest carry',
  },
  {
    name: 'Escalation / Hormuz Close',
    probability: 25,
    impacts: { oil: '+30-50%', spx: '-10-15%', vix: '+50-80%', energy: '+20-30%', tech: '-15-20%', defense: '+10-15%', gold: '+8-12%', usdjpy: '-5-8%' },
    bestPosition: 'Long Energy/Gold/Defense, Short Tech, Long JPY/CHF',
  },
]

// ============================================================================
// HELPERS
// ============================================================================
export function calcRR(entry, target, stop, direction = 'long') {
  if (direction === 'long') {
    const risk = entry - stop
    const reward = target - entry
    return risk > 0 ? (reward / risk).toFixed(1) : '--'
  }
  const risk = stop - entry
  const reward = entry - target
  return risk > 0 ? (reward / risk).toFixed(1) : '--'
}

export function isInEntryZone(price, low, high) {
  return price >= low && price <= high
}

export function checkAlerts(price, target, stop, direction = 'long') {
  if (direction === 'long') {
    if (price >= target) return 'TARGET_HIT'
    if (price <= stop) return 'STOP_HIT'
  } else {
    if (price <= target) return 'TARGET_HIT'
    if (price >= stop) return 'STOP_HIT'
  }
  return null
}
